name = "OneClient 1.21.11 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.11-fabric"
update-url = "oneclient/generated/performance-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "644e230019cfb1e2ecfc60540cb12c6ce9c85f04e2b3fe1ec067b0e4fea65ef7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
